'use client';

import Link from 'next/link';
import { FileText, ArrowLeft, ShieldCheck } from 'lucide-react';

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-100 font-sans p-6 md:p-12 selection:bg-cyan-500/30 selection:text-cyan-200">
      <div className="max-w-3xl mx-auto">
        
        {/* Navigation back to Main Application */}
        <div className="mb-8">
          <Link 
            href="/" 
            className="inline-flex items-center gap-2 text-xs font-mono text-slate-500 hover:text-cyan-400 transition"
          >
            <ArrowLeft className="h-4 w-4" /> BACK TO WORKSPACE
          </Link>
        </div>

        {/* Header Block */}
        <header className="border-b border-slate-900 pb-6 mb-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="h-9 w-9 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
              <FileText className="h-5 w-5" />
            </div>
            <h1 className="text-2xl font-black tracking-wider uppercase bg-gradient-to-r from-slate-100 to-slate-400 bg-clip-text text-transparent">
              Terms & Conditions Matrix
            </h1>
          </div>
          <p className="text-[10px] font-mono font-bold text-slate-500 uppercase tracking-widest">
            Last Updated: July 2026 • Structural Operating Guidelines
          </p>
        </header>

        {/* Matrix Legal Text */}
        <div className="space-y-6 text-sm text-slate-400 leading-relaxed font-sans">
          
          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">1. ACCEPTANCE OF TERMS</h4>
            <p>By accessing or using CircuitAI Studio, you agree to be bound by these Terms and Conditions. If you do not agree to all of the terms and conditions set forth herein, you are strictly prohibited from using the App and must discontinue use immediately.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">2. SERVICES AND AI DISCLAIMER</h4>
            <p>CircuitAI Studio leverages artificial intelligence models to process hardware specifications. The App provides generated output, including but not limited to, Bill of Materials (BOM), connection diagrams, and source code. <strong className="text-slate-200">THE AI OUTPUT IS PROVIDED FOR INFORMATIONAL PURPOSES ONLY.</strong> AI models may generate inaccurate or hazardous instructions. You must use caution and independent validation before building physical electronics.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">3. USER RESPONSIBILITIES</h4>
            <p>You are solely responsible for: the use and implementation of any designs or code generated by the App; ensuring the safety and legality of any physical hardware projects you build; compiling and flashing code onto microcontroller devices; and protecting your devices from hardware shorts or system bugs.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">4. INTELLECTUAL PROPERTY</h4>
            <p>The layout, design elements, interface tools, and underlying App architecture are the exclusive property of CircuitAI Studio. You retain ownership of your prompts, and we grant you a non-exclusive, worldwide, royalty-free license to use, modify, and run the generated code and connection arrays for your own personal or professional projects.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">5. PROHIBITED USES</h4>
            <p>You agree not to use the App: for any illegal, hazardous, or malicious purpose; to generate schematics or code for unsafe systems (e.g., weapons, life-support, critical infrastructure); or to reverse-engineer, decompile, or attempt to extract the source code of CircuitAI Studio itself.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">6. NO WARRANTY</h4>
            <p>CIRCUITAI STUDIO IS PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS. THE OPERATORS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE AI OUTPUT WILL BE SAFE, ACCURATE, OR UNINTERRUPTED.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">7. LIMITATION OF LIABILITY</h4>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL THE OPERATORS OF CIRCUITAI STUDIO BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING BUT NOT LIMITED TO: PHYSICAL INJURY, HARDWARE DAMAGE, PROPERTY DAMAGE, FIRE, OR ELECTRICAL HAZARDS RESULTING FROM THE USE OF AI-GENERATED SCRIPT OR BLUEPRINTS.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">8. INDEMNIFICATION</h4>
            <p>You agree to indemnify, defend, and hold harmless CircuitAI Studio, its operators, and third-party AI framework dependencies from and against any and all claims, damages, liabilities, costs, and expenses (including attorney's fees) arising from your use of the App or any violation of these Terms.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">9. THIRD-PARTY SERVICES</h4>
            <p>The App integrates with third-party systems (e.g., Google Gemini APIs). Your use of these processors is also subject to their respective terms and privacy models. The operators are not responsible for the availability, uptime, or sudden algorithmic changes of these external services.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">10. MODIFICATION OF TERMS</h4>
            <p>We reserve the right, in our sole discretion, to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting to the client UI. Your continued use of the App after the posting of changes constitutes your binding acceptance of those structural updates.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">11. GOVERNING LAW</h4>
            <p>These Terms shall be governed by and construed in accordance with standard data privacy protocols and local technological system operation regulations, without regard to its conflict of law principles.</p>
          </section>

          <section className="bg-slate-900/40 border border-slate-900 p-5 rounded-xl">
            <h4 className="font-mono font-bold text-slate-200 uppercase tracking-wide mb-2 text-xs text-cyan-400">12. TERMINATION</h4>
            <p>We reserve the right to restrict, suspend, or completely terminate your access to the App's compilation endpoints, without notice or liability, for any structural violation of these operational terms.</p>
          </section>

        </div>

        {/* Footer info element */}
        <footer className="mt-12 pt-6 border-t border-slate-900 text-center font-mono text-[10px] text-slate-600 tracking-wider">
          <p>&copy; 2026 CircuitAI Studio. All rights reserved.</p>
        </footer>

      </div>
    </main>
  );
}